#!/usr/bin/env bash

script_name="${0##*/}"

echo "${script_name}: '$(pwd)'"

progs="bash"
for p in ${progs}; do
	if ! test -x "$(command -v ${p})"; then
		echo "${script_name}: ERROR: Please install '${p}'." >&2
		result=1
	fi
done

if [[ ${result} ]]; then
	exit 1
fi

mkdir -p m4
exec autoreconf --force --install ${@}
